bce_weight: 0.2
cls_loss_weight: 1.0
dice_weight: 0.8
freeze_llm: true
hf_TrainingArguments:
  bf16: true
  dataloader_num_workers: 16
  eval_steps: 1000
  evaluation_strategy: steps
  learning_rate: 0.0001
  logging_dir: ${WEIGHTS_ROOT}/Step2_Finetune_Multimodal_abd_0512_r1_noncon/logs
  logging_steps: 500
  lr_scheduler_type: cosine
  max_grad_norm: 1.0
  max_steps: 15000
  output_dir: ${WEIGHTS_ROOT}/Step2_Finetune_Multimodal_abd_0512_r1_noncon/
  per_device_eval_batch_size: 1
  per_device_train_batch_size: 4
  remove_unused_columns: false
  save_steps: 3000
  warmup_steps: 2500
  weight_decay: 0.05
input_file: ${DATA_ROOT}/Sinai_ERMI_abd_train_val_noncontrast_0512.parquet
llm_args:
  bert_encoder_layers: 4
  model_class: BertModel
  model_id: Simonlee711/Clinical_ModernBERT
loss_combination_strategy: weighted_sum
loss_fct_seg: CombinedBCEDiceLoss
mixer_args:
  d_model: 768
  name: latent_mem
  nhead: 8
  num_layers: 1
  vision_as_mem: false
predict_transform:
- name: Resize
  spatial_size:
  - 256
  - 256
  - 256
pretrain_checkpoint: ${WEIGHTS_ROOT}/Step1_Pretrain_Seg_0328_abd/checkpoint-10000/model.safetensors
seg_loss_weight: 1.0
train_transform:
- name: RandFlip
  prob: 0.5
  spatial_axis: 0
- name: RandFlip
  prob: 0.5
  spatial_axis: 1
- name: RandFlip
  prob: 0.5
  spatial_axis: 2
- name: RandRotate90
  prob: 0.5
- mode: bilinear
  name: RandAffine
  prob: 0.5
  rotate_range:
  - 0.3
  - 0.3
  - 0.3
  scale_range:
  - 0.1
  - 0.1
  - 0.1
- name: Resize
  spatial_size:
  - 256
  - 256
  - 256
train_transform_imgonly:
- factors: 0.1
  name: RandScaleIntensity
  prob: 0.3
- name: RandShiftIntensity
  offsets: 0.1
  prob: 0.3
training_stage: finetune
use_3d_decoder: true
use_skip_connection: true
vision_args:
  feature_dim: 192
  llm_emb_dim: 768
  model_args:
    features_only: true
    global_pool: ''
    in_chans: 1
    model_name: tf_efficientnetv2_b0.in1k
    num_classes: 0
    pretrained: true
  model_class: EfficientNetViT
  nhead: 8
  seqlen: 514
