bce_weight: 0.2
cls_loss_weight: 0.0
dice_weight: 0.8
hf_TrainingArguments:
  bf16: true
  dataloader_num_workers: 16
  eval_steps: 500
  evaluation_strategy: steps
  learning_rate: 0.0001
  logging_dir: ${WEIGHTS_ROOT}/Step1_Pretrain_Seg_0328_abd/logs
  logging_steps: 500
  lr_scheduler_type: cosine
  max_grad_norm: 1.0
  max_steps: 10000
  output_dir: ${WEIGHTS_ROOT}/Step1_Pretrain_Seg_0328_abd/
  per_device_eval_batch_size: 1
  per_device_train_batch_size: 4
  remove_unused_columns: false
  save_steps: 2000
  warmup_steps: 1000
  weight_decay: 0.01
input_file: ${DATA_ROOT}/Sinai_ERMI_abd_train_val_0328_segmentation_v1.parquet
llm_args:
  bert_encoder_layers: 4
  model_class: BertModel
  model_id: Simonlee711/Clinical_ModernBERT
loss_combination_strategy: weighted_sum
loss_fct_seg: CombinedBCEDiceLoss
mixer_args:
  d_model: 768
  name: latent_mem
  nhead: 8
  num_layers: 1
  vision_as_mem: false
predict_transform:
- name: Resize
  spatial_size:
  - 256
  - 256
  - 256
seg_loss_weight: 1.0
train_transform:
- name: Resize
  spatial_size:
  - 256
  - 256
  - 256
training_stage: pretrain
use_3d_decoder: true
use_skip_connection: true
vision_args:
  feature_dim: 192
  llm_emb_dim: 768
  model_args:
    features_only: true
    global_pool: ''
    in_chans: 1
    model_name: tf_efficientnetv2_b0.in1k
    num_classes: 0
    pretrained: true
  model_class: EfficientNetViT
  nhead: 8
  seqlen: 514
